# Generated by Django 3.1.4 on 2020-12-27 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name="Ім'я")),
                ('description', models.TextField(max_length=500, verbose_name='Опис')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Дохід', 'Дохід'), ('Витрата', 'Витрата')], default='Витрата', max_length=7, verbose_name='Тип oперації')),
                ('value', models.IntegerField(default=100, max_length=10, verbose_name='Сума')),
                ('short_description', models.TextField(max_length=100, verbose_name='Короткий опис')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата виконання транзакції')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.category')),
            ],
        ),
    ]
