# Generated by Django 3.1.4 on 2021-01-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(choices=[('Дохід', 'Дохід'), ('Витрата', 'Витрата')], default='Витрата', max_length=10, verbose_name='Тип oперації'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='short_description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(default=100, verbose_name='Сума'),
        ),
    ]
