# Generated by Django 3.1.4 on 2021-01-09 21:37

from django.db import migrations


def change_category_name(apps, schema_editor):
    Category = apps.get_model('app', 'Category')
    queryset = Category.objects.all()

    for i in queryset:
        q = queryset.filter(name=i.name)
        if q.count() >= 2:
            i.name += '_' + str(i.id)
            i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210109_2132'),
    ]

    operations = [
        migrations.RunPython(change_category_name, reverse_code=migrations.RunPython.noop)
    ]
